CREATE SCHEMA 'tri_wln_trainingproject';
USE tri_wln_trainingproject;

CREATE  TABLE USERS (
  U_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR(45) UNIQUE NOT NULL ,
  PASSWORD VARCHAR(60) NOT NULL ,
  ENABLED TINYINT NOT NULL DEFAULT 1);

CREATE TABLE USER_ROLE (
  UR_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  U_ID INT NOT NULL,
  ROLE varchar(45) NOT NULL,
  UNIQUE KEY UID_ROLE (U_ID,ROLE),
  KEY U_ID_INDX (U_ID),
  FOREIGN KEY FK_U_ID (U_ID) REFERENCES USERS (U_ID));

CREATE SCHEMA `tri_wln_trainingproject_test` ;
USE tri_wln_trainingproject_test;

CREATE  TABLE USERS (
  U_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR(45) UNIQUE NOT NULL ,
  PASSWORD VARCHAR(60) NOT NULL ,
  ENABLED TINYINT NOT NULL DEFAULT 1);

CREATE TABLE USER_ROLE (
  UR_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  U_ID INT NOT NULL,
  ROLE varchar(45) NOT NULL,
  UNIQUE KEY UID_ROLE (U_ID,ROLE),
  KEY U_ID_INDX (U_ID),
  FOREIGN KEY FK_U_ID (U_ID) REFERENCES USERS (U_ID));